### ISSUE TITLE
WeChat会经常停止工作（就是崩溃了）

### ISSUE THREAD

**Issue by huxuyf** [bumandpunk/ntchat-wx#3]
相关错误信息如下：
问题事件名称:	APPCRASH
  应用程序名:	WeChat.exe
  应用程序版本:	3.6.0.0
  应用程序时间戳:	620de88f
  故障模块名称:	ntdll.dll
  故障模块版本:	6.1.7601.17514
  故障模块时间戳:	4ce7ba58
  异常代码:	c0000005
  异常偏移:	0002ff07
  OS 版本:	6.1.7601.2.1.0.256.48
  区域设置 ID:	2052
  其他信息 1:	41d9
  其他信息 2:	41d93f59f6a5e103ab90d77d38bf0e1e
  其他信息 3:	a4a6
  其他信息 4:	a4a6a582d1ad3aae023672334f19eb7b

**Comment by bumandpunk** [comment]
文档中有3.6.0.18下载地址，请使用该版本
