### ISSUE TITLE
ImportError: cannot import name 'wcprobe' from 'ntchat.wc' (E:\python program\ntchat-wx-3.6.0.18\ntchat\wc\__init__.py)

### ISSUE THREAD

**Issue by Unicornpeng** [bumandpunk/ntchat-wx#8]
您好，我在运行您的readme中的
#简单入门实例中给文件传输助手发一条消息的内容时，报错：ImportError: cannot import name 'wcprobe' from 'ntchat.wc' (E:\python program\ntchat-wx-3.6.0.18\ntchat\wc\__init__.py)，我打开__init__.py发现里面只有一个SUPPORT_VERSIONS = [
    '3.6.0.18'
]，并无'wcprobe'，请问如何处理？

**Comment by bumandpunk** [comment]
出现在这个错误的原因是因为你在github下载的源码目录中运行程序，因为wcprobe是根据python版本自动编译生成的，所以源码目录中没有这个文件.

你需要将要运行的例子文件移动到非源码目录下，再去运行或打包

**Comment by chenjiaming2qiqi** [comment]
我把send_text.py拷贝到d盘根目录。我运行这个例子文件还是报这个错，麻烦看看该怎么解决？

**Comment by bumandpunk** [comment]
> 我把send_text.py拷贝到d盘根目录。我运行这个例子文件还是报这个错误，麻烦看看怎么解决？

请再开个issues提供具体操作及报错信息
