### ISSUE TITLE
关于微信低版本登录问题

### ISSUE THREAD

**Issue by 18758527542** [bumandpunk/ntchat-wx#9]
目前要求的微信版本是3.6.0.18，但是在PC上安装这个版本的微信已经无法登录了，有什么好的解决办法吗？我从网上看修改微信版本来登录，使用之后会导致一些bug例如获取群信息时出现错误之类的，不知道应该怎么处理了

**Comment by bumandpunk** [comment]
可以选择使用低版本win服务器运行，或者尝试修改win版本
